# Generated by Django 3.2.9 on 2022-01-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='telegram_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
