# Generated by Django 3.2.10 on 2021-12-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_account_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
