# Generated by Django 3.2.10 on 2021-12-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_alter_account_telegram_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user',
            new_name='usr',
        ),
    ]
